export default {
    HOME: 'Home',
    BOOKING_LIST: 'BookingList',
    BOOKING_DETAIL: 'BookingDetail',
    CALENDAR: 'Calendar',
    ONBOARDING: 'Onboarding',
    PROFILE: 'Profile',
    REGISTER: 'Register',
    SETTINGS: 'Settings',
    SIGN_UP: 'SignUp',
    WALLET: 'Wallet',
    SIGN_IN: 'SignIn',
    APP: 'App',
    NOTIFICATION: 'Notification',
    MENU: 'Menu',
    CREATE_BOOKING: 'CreateBooking',
    PAYMENT: 'Payment',
    MESSAGE: 'Message',
    PERSONAL: 'Personal',
    LEADER_BOARD: 'LeaderBoard',
    CREATE_ACCOUNT: 'CreateAccount',
    CASH_IN: 'CashIn',
    CASH_OUT: 'CashOut',
    CONVERSATION_LIST: 'ConversationList',
    UPDATE_INFO_ACCOUNT: 'UpdateInfoAccount',
    BANK_ACCOUNT: 'BankAccount',
    BUSY_CALENDAR: 'BusyCalendar'
};
