export default {
    HOME: 'Trang chủ',
    BOOKING_LIST: 'Danh sách yêu cầu thuê',
    BOOKING_DETAIL: 'Chi tiết yêu cầu thuê',
    CALENDAR: 'Lịch',
    ONBOARDING: 'Onboarding',
    PROFILE: 'Trang cá nhân',
    REGISTER: 'Đăng ký',
    SETTINGS: 'Cài đặt',
    SIGN_UP: 'Đăng ký',
    WALLET: 'Ví',
    NOTIFICATION: 'Thông báo',
    MENU: 'Menu',
    CREATE_BOOKING: 'Tạo Yêu cầu thuê',
    PAYMENT: 'Thanh toán',
    MESSAGE: 'Trò chuyện',
    PERSONAL: 'Trang cá nhân',
    LEADER_BOARD: 'Bảng xếp hạng',
    CREATE_ACCOUNT: 'Tạo tài khoản',
    CASH_IN: 'Nạp Xu',
    CONVERSATION_LIST: 'Tin nhắn',
    UPDATE_INFO_ACCOUNT: 'Thông tin cá nhân',
    BANK_ACCOUNT: 'Tài khoản ngân hàng',
    BUSY_CALENDAR: 'Lịch bận',
    SUPPORT: 'Hỗ trợ',
    VERIFICATION: 'Xác thực tài khoản',
    SIGN_IN_WITH_OTP: 'Đăng nhập',
    FORGOT_PASSWORD: 'Quên mật khẩu',
    PARTNER_REGISTER: 'Đăng ký trở thành Host',
    CHANGE_PASSWORD: 'Đổi mật khẩu',
    PARTNER_DATA: 'Thông tin Host',
    CASH_OUT: 'Rút Xu',
    POLICY: 'Quy định chung',
    GUIDE: 'Hướng dẫn',
};
