export default {
    HOME: 'Trang chủ',
    BOOKING_LIST: 'Danh sách cuộc hẹn',
    BOOKING_DETAIL: 'Chi tiết cuộc hẹn',
    CALENDAR: 'Lịch',
    ONBOARDING: 'Onboarding',
    PROFILE: 'Trang cá nhân',
    REGISTER: 'Đăng kí',
    SETTINGS: 'Cài đặt',
    SIGN_UP: 'Đăng kí',
    WALLET: 'Rương kim cương',
    SIGN_IN: 'Đăng nhập',
    NOTIFICATION: 'Thông báo',
    MENU: 'Menu',
    CREATE_BOOKING: 'Tạo đơn hẹn',
    PAYMENT: 'Thanh toán',
    MESSAGE: 'Trò chuyện',
    PERSONAL: 'Trang cá nhân',
    LEADER_BOARD: 'Bảng xếp hạng',
    CREATE_ACCOUNT: 'Tạo tài khoản',
    CASH_IN: 'Nạp kim cương',
    CASH_OUT: 'Rút kim cương',
    CONVERSATION_LIST: 'Trò chuyện',
    UPDATE_INFO_ACCOUNT: 'Chỉnh sửa trang cá nhân',
    BANK_ACCOUNT: 'Tài khoản ngân hàng',
    BUSY_CALENDAR: 'Lịch bận',
    SUPPORT: 'Hỗ trợ',
    VERIFICATION: 'Xác thực tài khoản',
    SIGN_IN_WITH_OTP: 'Đăng nhập',
    FORGOT_PASSWORD: 'Quên mật khẩu'
};
