/* eslint-disable import/prefer-default-export */
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_DEVICE_TIMEZONE = 'SET_DEVICE_TIMEZONE';

export const SET_DEVICE_LOCALE = 'SET_DEVICE_LOCALE';

export const SET_TOKEN = 'SET_TOKEN';

export const SET_DEVICE_ID = 'SET_DEVICE_ID';

export const SET_LIST_BOOKING_LOCATION = 'SET_LIST_BOOKING_LOCATION';

export const SET_LIST_BANK = 'SET_LIST_BANK';

export const RESET_STORE_SIGN_OUT = 'RESET_STORE_SIGN_OUT';

export const SET_LIST_NOTIFICATION = 'SET_LIST_NOTIFICATION';

export const SET_CHATING_WITH = 'SET_CHATING_WITH';

export const SET_DATA_LISTENED = 'SET_DATA_LISTENED';

export const SET_MESSAGE_LISTENED = 'SET_MESSAGE_LISTENED';

export const SET_LIST_CONVERSATION = 'SET_LIST_CONVERSATION';

export const SET_NUMBER_MESSAGE_UNREAD = 'SET_NUMBER_MESSAGE_UNREAD';

export const SET_EXPO_TOKEN = 'SET_EXPO_TOKEN';
